Add project popup interaction
uuukiiiyooo/myFirstPortfolio.github.io pull request #6
Opened 2023-03-08 22:38 UTC by uuukiiiyooo

This branch updates the HTML file to create the project section dynamically and adds the Js code with the previous "project section" and the popup for the portfolio.

2023-03-08 22:45 UTC, prolajumokeoni commented
Hi @uuukiiiyooo,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters setup, please see the[ requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md#general-requirements)
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-08 22:54 UTC, uuukiiiyooo commented
Hi @prolajumokeoni! I don't know why github actions workflow is not working on branches, do you have any idea of what's happening? On main branch works just fine and it's the same files

2023-03-09 01:29 UTC, Reem-lab requested changes
# Hi Team, 👋🏻👋🏻

Good job so far!🤩✨💯🔥
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>
## Highlights
- Followed GitHub flow ✅
- No Linters error 🤩🔥💯
- Professional README 🔥✨💯💯
- Great working on the design and functionality 🔥🤩💯

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 01:29 UTC, Reem-lab commented on scripts.js
> +            </div>
- [ ] Great job working on the functionality so far but I think it would be great if you also add the pop up for all the cards so you need to also generate it for all since it is one of the requirements because I saw it is just implemented for the first card so kindly implement this to make your Project complete 🤩🔥🔥


![image](https://user-images.githubusercontent.com/58553711/223891367-127d9d6d-d013-4405-8a55-280a9610e0e4.png)

2023-03-09 02:47 UTC, Owusu-Desmond requested changes
Hi @uuukiiiyooo and @muneeb3123  :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 02:47 UTC, Owusu-Desmond commented on scripts.js
> +                    </ul>
- [ ] While working on the changes the previous reviewer suggested, Why don't you use JavaScript [forEach()](https://www.w3schools.com/jsref/jsref_foreach.asp) to iterate over the array of objects to create each popup or card dynamically? Now assuming you have 50 projects, are you going to create these whole cards or popups manually :smile: So please make sure that you iterate over the array of objects to create them dynamically to even make your code clean :+1:

2023-03-09 03:00 UTC, uuukiiiyooo commented on scripts.js
> +                    </ul>
Hello @Owusu-Desmond! I think this is not on the project's requirements, I do understand your point but don't you think it coul've been an optional suggestion?

2023-03-09 19:46 UTC, AbayomiOlaoye approved these changes
Hi @uuukiiiyooo :partying_face: :clap:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- Linter checks are passing :heavy_check_mark: 
- Professional ReadMe documentation :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 19:59 UTC, merged